<a href="https://colab.research.google.com/github/sucheerarighthere/BasicProg_DataViz65/blob/main/midterm_cheat_sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###แกรมแก๊บแตง เพอร์เฟค!!!!!!
สรุป ที่ต้องสอบภายใน midterm
1. variable operation
2. print
3. string operations 
4. list
5. dictionary 
6. numpy arrey
7. function
8. looping condition
9. pandas: read_csv , head() , tail() .indexing
10. slicing - query
11. missing value , looping ,functionsที่จำเป็น
12. concat merge groupby 
13. create pandas table 

###STring Operationg

In [4]:
# Find and search
s = 'mountain'

print(s.startswith('moun'))
print(s.endswith('in'))
print(s.find('n')) #หาตัวอักษร n อยู่ที่ไหน  เลข บวกไปอีก
print(s.rfind('n')) #rfind() เป็นการค้นหาจากด้านหลังจากตำแห่งแรกที่พบเช่นกัน
print(s.replace('moun', 'con')) #แทนที่ moun ด้วย con
print(s.count('a'))

True
True
3
7
contain
1


In [7]:
s = 'this is a game that i love to play.'

print(s.capitalize()) #ใช้สำหรับทำให้ตัวอักษรตัวแรกของ String เป็นตัวพิมพ์ใหญ่
print(s.title()) # นั้นจะทำให้ตัวแรกในทุกๆ คำที่คั่นด้วย white space เป็นตัวพิมพ์ใหญทั้งหมด
print(s.upper()) #แปลงให้ตัวอักษรทุกตัวใน String เป็นตัวพิมพ์ใหญ่
print('MARCUSCODE.COM'.lower()) #แปลงให้ตัวอักษรทุกตัวใน String เป็นตัวพิมพ์เล็ก

This is a game that i love to play.
This Is A Game That I Love To Play.
THIS IS A GAME THAT I LOVE TO PLAY.
marcuscode.com


In [8]:
s = 'Python'
print(s.center(10)) #ใช้สำหรับเติมข้อความเข้าไปทางซ้ายและทางขวาให้ String มีความยาวกับที่ระบุ
print(s.ljust(10)) #ชิดซ้าย
print(s.rjust(10)) #ชิดขวา 
print(s.center(10, '#')) #เติมข้อความด้วยแฮชแทก
print(s.ljust(10, '#')) #เติมข้อความด้วยแฮชแทก
print(s.rjust(10, '#'))

number = '83'
print(number.zfill(6)) #ป็นการใช้เติมตัวเลข 0 โดยเรามักจะใช้กับ String ที่มีรูปแบบเป็นตัวเลข
print('-1.32'.zfill(8))

  Python  
Python    
    Python
##Python##
Python####
####Python
000083
-0001.32


In [9]:
s = '    Python '
print(s.strip()) #ตัดคำออกจากข้อความ
print(s.lstrip())
print(s.rstrip())

s2 = '----marcuscode----'
print(s2.strip('-'))
print(s2.lstrip('-'))
print(s2.rstrip('-'))

Python
Python 
    Python
marcuscode
marcuscode----
----marcuscode


In [10]:
# tesing true
print('marcuscode2017'.isalnum())
print('bobby'.isalpha())
print('1234'.isdecimal())
print('1234'.isdigit())
print('1234'.isnumeric())
print('mateo'.islower())
print('MATEO'.isupper())

# tesing false
print('marcuscode 2017'.isalnum()) # has space
print('bobby1'.isalpha()) # has number
print('7F'.isdecimal()) # F is not decimal
print('1234A'.isdigit()) # A is not digit
print('Python'.isnumeric()) # not number
print('Mateo'.islower()) # M is upper case
print('Mateo'.isupper()) # Not all are upper case

True
True
True
True
True
True
True
False
False
False
False
False
False
False


###List
list เอาไว้รวม string และ รวมด้วย join() หรือการตัดคำออกจาก String ด้วยsplit()

In [41]:
countries = ['England', 'Turkey', 'Poland', 'Russia', 'Germany']
print(', '.join(countries))
# ตัวแปร ประเทศ สำหรับเก็บข้อมูลประเทศต่างๆ 
#ปริ้น countries แล้ว ขั้นด้วย , 
lang = 'Java PHP C++ Python C#'
print(lang.split(' '))
#lang นั้นเป็นข้อความที่คั่นด้วยช่องว่าง
# split()แยก String ออกจากตัวแปรและจะได้ผลลัพธ์เป็นลิสต์ สามารถใช้ตัวอื่นแทน '' ได้ 


text = 'Python is a language\nused to create a web,\n'
text += 'desktop application\nand more'
text2 = text.splitlines() #สำหรับเมธอด splitlines() เป็นการแบ่ง String ด้วยการขึ้นบรรทัดใหม่
for t in text2:
    print(t)

England, Turkey, Poland, Russia, Germany
['Java', 'PHP', 'C++', 'Python', 'C#']
Python is a language
used to create a web,
desktop application
and more


การประกาศและใช้งาน List
list เป็นตัวแปรประเภทหนึ่ง การประกาศลิสต์ ข้อมูลจะอยู่ ใน [] และคั่นสมาชิกแต่ละตัว ด้วย , 

In [42]:
numbers = [-1, 2, 5, 8, 10, 13] #ลิสต์จำนวนเต็ม 6 ตัว
names = ['Mateo', 'Danny', 'James', 'Thomas', 'Luke'] #List ของ String ที่สำหรับเก็บชื่อและมี 5 รายชื่อ
mixed_type = [-2, 5, 84.2, "Mountain", "Python"] #mixtype ในลิสต์เดียว สามารถเก็บได้ทั้งตัวเลขและตัวอักษร

In [43]:
numbers = [] #ตอนแรกในลิสต์ไม่มีตัวเลข
numbers.append(-1) #append() เพื่อเพิ่มข้อมูลใหม่เข้าไปใน List 
numbers.append(2)
numbers.append(5) #ชื่อลิสต์.operation
numbers.append(8)
numbers.append(10)
numbers.append(13)

names = ['Mateo', 'Danny']
names.append('James')
names.append('Thomas')
names.append('Luke')

print(numbers) 
print(names)

print('numbers count = ', len(numbers))
print('names count = ', len(names)) #ใช้เพื่อนับจำนวนสมาชิกภายใน List

[-1, 2, 5, 8, 10, 13]
['Mateo', 'Danny', 'James', 'Thomas', 'Luke']
numbers count =  6
names count =  5


การเข้าถึงข้อมูลภายในlist

In [44]:
names = ['Mateo', 'Danny', 'James', 'Thomas', 'Luke'] #ลำดับสมาชิกมีความสำคัญ
print('names[0] = ', names[0]) #สมาชิกลำดับที่ 1
print('names[3] = ', names[3])
print('names[-1] = ', names[-1]) #สมาชิกตัวที่ 1นับมาจากข้างหลัง

# update value
names[0] = 'Bob'
print('names[0] = ', names[0])
#Index ของ List นั้นเริ่มต้นจาก 0

names[0] =  Mateo
names[3] =  Thomas
names[-1] =  Luke
names[0] =  Bob


อ่านคำสั่งในลิสต์ ด้วยคำสั่ง for loop 

In [45]:
numbers = [10, 20, 30, 40, 50, 60, 70]
sum = 0
for n in numbers: #เพื่อประกาศว่า n คือ สมาชิกในลิสต์ ลูปในลิสต์numbers
    print(n, end =' ')
    sum += n

print('sum = ', sum)

names = ['Mateo', 'Danny', 'James', 'Thomas', 'Luke']
for i in range(0, len(names)): #range คือ Index จาก 0 ถึงขนาดตัวสุดท้ายของ List #lem นัลจำนวนในสมาชิก
    print(names[i].upper(), end ='/')#เว้นด้วย /
    print(names[i].upper(), end ='=')#เว้นด้วย =
    # ใน for เดียวกัน จะถือว่าอยู่ในคำสั่งเดียวกัน 

10 20 30 40 50 60 70 sum =  280
MATEO/MATEO=DANNY/DANNY=JAMES/JAMES=THOMAS/THOMAS=LUKE/LUKE=

List slicing
เราสามารถตัดข้อมูลจากลิสต์หนึ่ง นำมาสร้งเป็นลิสต์ใหม่ได้

In [49]:
ch = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

a = ch[0:4] # a - d #แปลว่า สร้างลิสต์ a ด้วย สมาชิกตัวที่ 1-5 จากลิสต์ ch
b = ch[4:9] # e - h
c = ch[:3] # a - c 
d = ch[3:] # c - h
e = ch[:] #เอาทุกตัวในลิสต์ 
f = ch[0:2] + ch[6:8] # a - b and g - h
g = ch # or equivalent to e = ch 

print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)

['a', 'b', 'c', 'd']
['e', 'f', 'g', 'h']
['a', 'b', 'c']
['d', 'e', 'f', 'g', 'h']
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']
['a', 'b', 'g', 'h']
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']


การใช้งานคำสั่ง del เพื่อลบข้อมูลใน List

In [50]:
ch = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']

del ch[0] # delete a 
print(ch)

del ch[0] # delete b 
print(ch)

del ch[2:4] # delete e, f 
print(ch)

del ch[:] # delete all
print(ch)
#ตัดออกมาเรื่อยๆ

['b', 'c', 'd', 'e', 'f', 'g', 'h']
['c', 'd', 'e', 'f', 'g', 'h']
['c', 'd', 'g', 'h']
[]


การใช้งานเมธอดของ List

In [52]:
names = ['David', 'Johnny', 'Dennis', 'Jason']

# add 2 names to the end of the list
names.append('Andy') #เพิ่ม แอนดี้ลงไปในลิสต์เนม 
names.append('Rene')
print(names)

# add a name at position 3 เพื่อเพิ่มสมาชิกไปยังตำแหน่งที่ต้องการ
names.insert(2, 'Mike') 
print(names)

# remove 2 specific names เพื่อนำออกข้อมูลใน List เราได้ทำการลบสองรายชื่อ คือ 'David' และ 'Johnny' ออกไปจาก List
names.remove('David')
names.remove('Johnny') #สามารถ ใช้ ลูกน้ำเพื่อขั้นได้
print(names)

# pop the last item fro the list นำข้อมูลที่อยู่ท้ายสุดของ List และส่งค่านั้นกลับมา
print('Popped item =', names.pop()) 
print(names)
print('เหมือนว่าปริ้นแค่สมาชิกตัวเดียว ตัวสุดท้าย')
print('Popped item =', names.pop())
print(names)

# clear all items
names.clear()
print(names)

['David', 'Johnny', 'Dennis', 'Jason', 'Andy', 'Rene']
['David', 'Johnny', 'Mike', 'Dennis', 'Jason', 'Andy', 'Rene']
['Mike', 'Dennis', 'Jason', 'Andy', 'Rene']
Popped item = Rene
['Mike', 'Dennis', 'Jason', 'Andy']
เหมือนว่าปริ้นแค่สมาชิกตัวเดียว ตัวสุดท้าย
Popped item = Andy
['Mike', 'Dennis', 'Jason']
[]


In [53]:
fruits = ['banana', 'orange', 'apple', 'grape', 'apple', 'peach']

print(fruits)

print('%d apples in list' % fruits.count('apple')) #แปล%เป็นจำนวนแอปเปิ้ล แล้วก้ปริ้น
print('%d banana in list' % fruits.count('banana'))

print('Index of grape is %d' % fruits.index('grape'))

fruits.sort() #ใช้สำหรับเรียงข้อมูลภายใน List ตามตัวอักษรจากก่อนไปทีหลัง
print('Sorted', fruits)

fruits.reverse() #เรียงกลับ 
print('Reversed', fruits)

['banana', 'orange', 'apple', 'grape', 'apple', 'peach']
2 apples in list
1 banana in list
Index of grape is 3
Sorted ['apple', 'apple', 'banana', 'grape', 'orange', 'peach']
Reversed ['peach', 'orange', 'grape', 'banana', 'apple', 'apple']


การใช้งานฟังก์ชั่นกับlist

In [56]:
numbers = [12, 3, 1, -5, 8, 3, -2, 10]

print('%d numbers in list' % len(numbers)) #นับจำนวนเobjectใน list 
print('Min number = %d' % min(numbers))
print('Max number = %d' % max(numbers)) #หาค่าที่มากที่สุด

8 numbers in list
Min number = -5
Max number = 12


In [57]:
#กรณีถ้าเป็นตัวเลขแบบไม่มีทศนิยมให้ใช้ %d
# ส่วน %s สำหรับข้อความ 
# %f สำหรับตัวเลขที่มีทศนิยม
d = 199
s = 'Hello, Python'
f = 58.36
print('d = %d' %(d))
print('s = %s' %(s))
print('f = %.2f' %(f))

d = 199
s = Hello, Python
f = 58.36


In [67]:
print(list(range(0, 20, 4))) #( เริ่มจาก , สิ้นสุด , ห่างจาก)

tuple1 = (1, 2, 3, 4, 5) 
print(list(tuple1))

[0, 4, 8, 12, 16]
[1, 2, 3, 4, 5]


## Dictionary

In [68]:
#สมาชิกของดิก จะอยู่ใน ปีกกา 
scores = {'james': 1828, 'thomas': 3628, 'danny': 9310}
scores['bobby'] = 4401
#Dictionary แต่ละตัวจะถูกกำหนดในรูปแบบ key: value 

numbers = {1: 'One', 2: 'Two', 3: 'Three'}

print(scores)
print(numbers)

{'james': 1828, 'thomas': 3628, 'danny': 9310, 'bobby': 4401}
{1: 'One', 2: 'Two', 3: 'Three'}


In [69]:
{'james': 1828, 'thomas': 3628, 'danny': 9310, 'bobby': 4401}
{1: 'One', 2: 'Two', 3: 'Three'}

{1: 'One', 2: 'Two', 3: 'Three'}

การเข้าถึงข้อมูลภายใน Dictionary

In [70]:
scores = {'james': 1828, 'thomas': 3628, 'danny': 9310, 'bobby': 4401}

# display data
print('james =>', scores['james'])
print('thomas =>', scores['thomas'])
print('danny =>', scores['danny'])
print('bobby =>', scores['bobby'])

# update data
scores['james'] = scores['james'] + 1000
scores['thomas'] = 100

print('james =>', scores['james'])
print('thomas =>', scores['thomas'])

james => 1828
thomas => 3628
danny => 9310
bobby => 4401
james => 2828
thomas => 100


```การอ่านค่าใน Dictionary ด้วยคำสั่ง For loop```

---





คำสั่ง For loop นั้นเป็นคำสั่งที่ยืดหยุ่นและสามารถใช้งานได้อย่างหลากหลาย ในการอ่านค่าใน Dictionary นั้นเราสามารถใช้ For loop เพื่อวนอ่านค่าทั้ง Key และ Values ใน Dictionary ได้ มาดูตัวอย่างของโปรแกรม

In [77]:
countries = {'de': 'Germany', 'ua': 'Ukraine',
             'th': 'Thailand', 'nl': 'Netherlands'}
#ใน { 'key':'value'} 
for k, v in countries.items():#ใน { 'key':'value'} 
    print(k, v)

# iterate through keys เอาแค่คีย์ในดิก
print('\nKey:', end = ' ')
for k in countries.keys():
    print(k, end = ' ')

# iterate through values เอาแค่แวลู่ในดิก
print('\n\nValue:', end = ' ') #\n เว้นบรรทัด สองครั้งก็สองบรรทัด
for v in countries.values():
    print(v, end = ' ')

de Germany
ua Ukraine
th Thailand
nl Netherlands

Key: de ua th nl 

Value: Germany Ukraine Thailand Netherlands 

Methods	Description

---
1. clear()	ลบข้อมูลทั้งหมดภายใน Dictionary
2. copy()	คัดลอก Dictionary ทั้งหมดไปยังอันใหม่
3. get(key[, default])	ส่งค่าข้อมูลใน Dictionary จาก Key ที่กำหนด ถ้าหากไม่มี Key อยู่และไม่ได้กำหนด default จะทำให้เกิดข้อผิดพลาด `KeyError`
4. items()	ส่งค่ากลับเป็นออบเจ็คของ Key และ Value
5. keys()	ส่งค่ากลับเป็น List ของ Key ทั้งหมดใน Dictionary
6. pop(key[, default])	ส่งค่ากลับเป็นค่าสุดท้ายใน Dictionary
7. popitem()	ส่งค่ากลับเป็น Tuple ออบเจ็คของ Key และ Value
8. setdefault(key[, default])	ส่งค่ากลับเป็นค่าของ Key ที่กำหนด ถ้าหากไม่มี Key อยู่ใส่ข้อมูลเข้าไปใน Dictionary
9. update([other])	อัพเดท Dictionary กับคู่ของ Key และ Value จากออบเจ็คอื่น และเขียนทับ Key ที่มีอยู่
10. values()	ส่งค่ากลับเป็น List ของ Value ทั้งหมดใน Dictionary




## Numpy array

---

NumPy เป็นชื่อของ library ที่ใช้ในการคำนวนทางคณิตศาสตร์ในภาษา Python ซึ่งภายในถูกเขียนด้วยภาษา C จึงทำงานได้เร็วและมีประสิทธิภาพ โดย NumPy มีความสามารถในการจัดการกับอาเรย์หลายมิติและข้อมูลแบบเมทริกซ์

In [79]:
import numpy as np
a = np.array([1,2,3])
print(a)        # [1 2 3]
print(type(a))  # <class 'numpy.ndarray'>

[1 2 3]
<class 'numpy.ndarray'>


In [80]:
import numpy

In [81]:
mat_a = numpy.array([[2,4,5],[1,2,3],[9,8,7],[3,6,9]])
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [82]:
list_a = [[2,4,5],[1,2,3],[9,8,7],[3,6,9]]

In [95]:
import numpy as np
list_b = [[-1,-1,2,4,5],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]] #จำนวนเลขในเมทริกซ์ต้องเท่ากัน เพราะเมทริกซ์เป็นจัตุรัส
mat_b = np.array(list_b) #เรียกตัวเลขจากลิสต์บีที่เป็นarray เรียงเป็นเมทริกซ์ --->array 2มิติ
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

In [97]:
import numpy as np        # วิธีการที่จะเรียกใช้ numpy library โดยกำหนดชื่อย่อว่า np

a = np.array([1, 2, 3])   # สร้าง array 1 มิติ (เวกเตอร์) จาก Python list [1, 2, 3]
print(type(a))            # พิมพ์ "<class 'numpy.ndarray'>"
print(a.shape)            
# shape เป็น method ที่ไว้เรียกดูขนาดของ array 
# พิมพ์ "(3,)" แปลว่าเป็น array 1 มิติ ที่มีสมาชิกเท่ากับ 3 (เวกเตอร์ที่ความยาวเท่ากับ 3)

print(a[0], a[1], a[2])   # พิมพ์ "1 2 3" สมาชิกของเอตัวที่1 สมาชิกของเอ
a[0] = 5                  # เปลี่ยนค่าใน array เปลี่ยนสมาชิกของเอตัวที่ 1 เป็น 5 
print(a)                  # พิมพ์ "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # สร้าง array 2 มิติ (เมตริกซ์2x3)
print(b.shape)                     # พิมพ์ "(2, 3)" แปลว่าเป็น array 2 มิติ ที่มีความยาวเท่ากับ 2 และ 3 ตามลำดับ
                                   # พูดง่ายๆ ว่าเป็นเมตริกซ์ขนาด 2x3 นั่นเอง 
print(b[0, 0], b[0, 1], b[1, 0])   # พิมพ์ "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


numpy operations

In [99]:
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# [[ 1  2] + [[ 5  6] =  [[ 6  8]
#   [3 4]]    [ 7  8]]    [10 12]]
print(x + y)

# [[-4 -4]
#  [-4 -4]]
print(x - y)

# [[ 5 12]
#  [21 32]]
print(x * y)

# ตัวอย่างการหาร เมื่อเลขไม่ลงตัว สมาชิกใน array จะเปลี่ยนเป็นจำนวนจริงโดยอัตโนมัติเหมือนกรณีการหารตัวเลข (ดูหัวข้อบน)
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)

# ยกกำลัง
print(x ** 2)

# ถอดรากที่สองมีสองวิธีคือเรียกฟังก์ชั่นของ numpy หรือ ยกกำลังด้วย 1/2
print(np.sqrt(x))
print(x ** (1/2))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 1  4]
 [ 9 16]]
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


## Function
def เพื่อนิยาม Python function

In [100]:
def hello(name):
    print('Hello %s' % name)

def count_vowel(str): #กำหนดฟังก์ชั่น count vowel นับสระ  ให้เป็น สตริง ตัวหนังสือ
    vowel = 0
    for c in str: #สำหรับตัวแปร c ในตัวหนังสือ 
        if c in ('A', 'E', 'I', 'O', 'U', 'a', 'e', 'i', 'o', 'u'):
            vowel = vowel + 1
    return vowel

def area(width, height): #กำหนดให้ฟังด์ชั่น พื้นที่ มีด้านกว้างและด้านยาว 
    c = width * height
    return c

# calling functions
hello('Danny')
hello('Mateo')
print('Vowel in string = %d' % count_vowel('marcuscode.com')) #นับสระจากคำในวงเล็บ
print('Vowel in string = %d' % count_vowel('Python'))
print('Area = %d' % area(8, 4))

Hello Danny
Hello Mateo
Vowel in string = 5
Vowel in string = 1
Area = 32


In [101]:
def sign(x): #สัญลักษณ์
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else: #อื่นๆที่มากกว่าหรือน้อยกว่า 0 คือ เท่ากับ 0
        return 'zero'

for x in [-1, 0, 1,5,6,8,0]:
    print(sign(x))
# พิมพ์ "negative", "zero", "positive"

negative
zero
positive
positive
positive
positive
zero


In [102]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # พิมพ์ "Hello, Bob"
hello('Fred', loud=True)  # พิมพ์ "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


## looping condition

In [104]:
data = int(input("ใส่เลขที่ต้องการ: "))
digit = 3
if data == digit:
    print ("เท่ากัน",end="")
elif data < digit:
    print("น้อยกว่า",end="")
else:
    print ("ผิดนะจ๊ะ",end="")

ใส่เลขที่ต้องการ: 50
ผิดนะจ๊ะ

In [115]:
#คำสั่ง for loop สามารถเขียนได้รูปแบบดังนี้

i = 0
for i in range(7): #เรียงลำดับไป7
   print (i,"eiei",end="   ")

0 eiei   1 eiei   2 eiei   3 eiei   4 eiei   5 eiei   6 eiei   

In [116]:
	
for x in 'HelloWorld': print (x)

H
e
l
l
o
W
o
r
l
d


In [123]:

interval = 0
while (interval <=10):
    print ("count:", interval)
    interval = interval+2 #ทีละ 2

count: 0
count: 2
count: 4
count: 6
count: 8
count: 10


##pandas: read_csv , head() , tail() .indexing
Panel Data (ชุดข้อมูลหลายมิติ)

1. การอ่านไฟล์ CSV .read_csv(‘ชื่อไฟล์.csv’)
2. .head(‘จำนวน row ที่อยากได้ออกมาแสดงนับจากแถวบนสุด’)
3..tail(‘จำนวน row ที่อยากได้ออกมาแสดงนับจากแถวล่างสุด’) การดูข้อมูลจากแถวล่างสุด 
4. .describe() =การหาค่า (count, mean ,std ,min ,25% ,50% ,75%, max)ของข้อมูลแต่ละ column
5. categories() categories นั้นจะไม่นับตัวซ้ำว่าเป็นอีก 1 categories
6. .DataFrame(ตัวแปร dict) การสร้าง Dataframe สามารถทำได้ด้วยคำสั่ง


