<a href="https://colab.research.google.com/github/sucheerarighthere/BasicProg_DataViz65/blob/main/Recap_4_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Matrix Slicing

In [ ]:
import numpy 

In [ ]:
mat_a = numpy.array([[2,4,5],[1,2,3],[9,8,7],[3,6,9]])
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [ ]:
list_a = [[2,4,5],[1,2,3],[9,8,7],[3,6,9]]
mat_a = numpy.array(list_a)
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [ ]:
import numpy as np


In [ ]:
list_b = [[-1,-1,2,4,5],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_b = np.array(list_b)
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

## Quiz2

1. slice ค่าลบออกมาจาก ```mat_b```
2. slice ```[1,2,3]``` จาก ```mat_a```
3. slice ```[[1,3],[9,7],[3,9]]``` ออกมาจาก ```mat_b```

In [ ]:
mat_b[-5:,:2] 


array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

In [ ]:
mat_a[1:2]

array([[1, 2, 3]])

In [ ]:
mat_b[1:,2::2]

array([[1, 3],
       [9, 7],
       [3, 9]])

##Function ```Print```

In [ ]:
print()

In [ ]:
print('สวัสดี')

สวัสดี


In [ ]:
print('hello')
print('สวัสดี')

hello
สวัสดี


In [ ]:
print('hello',end=' ')
print('สวัสดี')

hello สวัสดี


In [ ]:
print('hello','สวัสดี')

hello สวัสดี


In [ ]:
print('hello','สวัสดี',sep='\n')

hello
สวัสดี


In [ ]:
print('hello',end='')
print('สวัสดี')

helloสวัสดี


HW1 

เขียน function 
แสดงความต่างของเวลา (Quiz1)
โดย input อยู่ในรูปแบบ ```'09:11:50 - 12:30:15'```

และทดลองรัน

* '09:11:50 - 12:30:15'
* '13:41:07 - 20:00:18'
* '00:00:00 - 23:59:59'

In [ ]:
def print_Time(time) : #def ซึ่งก็ย่อมาจาก definition ซึ่งแปลว่าการนิยาม
      x= time
      y=x.split(' - ')
      z0=y[0].split(':') #แยกตัวที่0คือตัวที่1ก่อน: (split คือการแยก string)
      z1=y[1].split(':') #แยกตัวที่1คือตัวที่2ก่อน:
      print(y) #เหมือนการแทนที่ด้วยสมการเรื่อยๆ
      print(z0)
      print(z1)
      timesecond=((int(z1[0])*3600)+(int(z1[1])*60)+(int(z1[2])))-((int(z0[0])*3600)+(int(z0[1])*60)+(int(z0[2])))
      print(f'ความต่างของเวลา = {timesecond:,} วินาที') #ถ้าใส่ลลูกน้ำ,แล้วจะเป็นการใส่หลักทศนิยม

In [ ]:
print_Time('09:11:50 - 12:30:15')

['09:11:50', '12:30:15']
['09', '11', '50']
['12', '30', '15']
ความต่างของเวลา = 11,905 วินาที


In [ ]:
print_Time('13:41:07 - 20:00:18')

['13:41:07', '20:00:18']
['13', '41', '07']
['20', '00', '18']
ความต่างของเวลา = 22,751 วินาที


In [ ]:
print_Time('00:00:00 - 23:59:59')

['00:00:00', '23:59:59']
['00', '00', '00']
['23', '59', '59']
ความต่างของเวลา = 86,399 วินาที


#เฉลยตามอาจารย์HW1 

เขียน function 
แสดงความต่างของเวลา (Quiz1)
โดย input อยู่ในรูปแบบ ```'09:11:50 - 12:30:15'```

และทดลองรัน

* '09:11:50 - 12:30:15'
* '13:41:07 - 20:00:18'
* '00:00:00 - 23:59:59'

In [ ]:
input = '09:11:50 - 12:30:15'
input

'09:11:50 - 12:30:15'

In [ ]:
input_split = input.split(' - ')
input_split

In [ ]:
starttimeSP = input_split[0].split(':')
endtimeSP = input_split[-1].split(':')
print(starttimeSP,endtimeSP,sep='\n')

['09', '11', '50']
['12', '30', '15']


In [ ]:
def calculate_time(input):
    input_split = input.split(' - ')
    starttimeSP = input_split[0].split(':')
    endtimeSP = input_split[-1].split(':')

    starttime = 3600*int(starttimeSP[0]) + 60*int(starttimeSP[1]) + int(starttimeSP[2])
    endtime = 3600*int(endtimeSP[0]) + 60*int(endtimeSP[1]) + int(endtimeSP[2])

    print(f'ระยะเวลาระหว่าง {input_split[0]} และ {input_split[1]} ห่างกันเท่ากับ {endtime-starttime:,} วินาที')

In [ ]:
calculate_time('09:11:50 - 12:30:15')

ระยะเวลาระหว่าง 09:11:50 และ 12:30:15 ห่างกันเท่ากับ 11,905 วินาที


In [ ]:
calculate_time('13:41:07 - 20:00:18')

ระยะเวลาระหว่าง 13:41:07 และ 20:00:18 ห่างกันเท่ากับ 22,751 วินาที


# Quiz3

เขียน function แสดงความต่างของเวลาโดย input อยู่ในรูปแบบ 'XX:YY:ZZ - AA:BB:CC'

และวนลูปแสดงผลของ input ต่อไปนี้

* '09:11:50 - 12:30:15'
* '13:41:07 - 20:00:18'
* '00:00:00 - 23:59:59'
* '18:04:11 - 00:00:00'
* '21:30:00 - 03:05:15'

ตัวอย่าง input ```'00:00:00-01:00:00'```

output ```ช่วงระยะเวลาระหว่าง 00:00:00 ถึง 01:00:00 มีเวลาทั้งหมด 3,600 วินาที```

SyntaxError: ignored